# Generated by Django 6.0.2 on 2026-02-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('min_cgpa', models.FloatField()),
                ('max_income', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('deadline', models.DateField()),
            ],
        ),
    ]
