# Generated by Django 6.0.2 on 2026-02-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='state',
            field=models.CharField(default='All', max_length=100),
            preserve_default=False,
        ),
    ]
